# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0006_auto_20170416_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRepo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
