# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0007_solicitudes_usuariosapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosapp',
            name='listaSolicitudes',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
