# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0008_usuariosapp_listasolicitudes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosapp',
            name='listaSolicitudes',
        ),
    ]
