# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0010_auto_20170507_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='creador',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
